mysql:
  db:
    extra:
      config:
        min-idle: 10
        max-pool-size: 50

#----------------------------------------------------------------------
# Logging Configuration File Path
#----------------------------------------------------------------------
logging:
  config: classpath:config/log-local.xml