#----------------------------------------------------------------------
# DB & Redis & document db
#----------------------------------------------------------------------
spring:
  data:
    mongodb:
      #uri: mongodb://local_conn:Wconcept!%4034conn@item-dev-docdb.cluster-cdppg5dgajqc.ap-northeast-2.docdb.amazonaws.com:27017/wck_coupon?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      auto-index-creation: false
      host: item-dev-docdb.cluster-cdppg5dgajqc.ap-northeast-2.docdb.amazonaws.com
      port: 27017
      username: local_conn
      password: Wconcept!@34conn
      database: wck_coupon
      replica-set-name: rs0
      uuidRepresentation: STANDARD
      ssl:
        enabled: true
      autoIndexCreation: false
      minSize: 5
      maxSize: 10
      maxConnecting: 10
      maxConnectionLifeTime: 1
      connectTimeout: 30
      readTimeout: 30